wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1710988402.31517
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      - 77
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      - 77
      3:
      - 7
      - 13
      - 23
      - 33
      4: 3.11.4
      5: 0.15.7
      6: 4.35.0
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: lr-Adam
      5: 1
      6:
      - 1
    - 1: train_auroc
      5: 1
      6:
      - 1
    - 1: train_ap
      5: 1
      6:
      - 1
    - 1: train_loss_step
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: valid_loss_step
      5: 1
      6:
      - 1
    - 1: valid_auroc
      5: 1
      6:
      - 1
    - 1: valid_ap
      5: 1
      6:
      - 1
    - 1: valid_loss_epoch
      5: 1
      6:
      - 1
    - 1: train_loss_epoch
      5: 1
      6:
      - 1
learning_rate:
  desc: null
  value: 0.0001
node_dim:
  desc: null
  value: 772
out_chan:
  desc: null
  value: 64
num_heads:
  desc: null
  value: 8
edge_dim:
  desc: null
  value: 1
encoder_layers:
  desc: null
  value: 6
