wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.7
    framework: huggingface
    huggingface_version: 4.35.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712860554.820369
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 75
      - 77
      3:
      - 13
      - 23
      4: 3.11.4
      5: 0.15.7
      6: 4.35.0
      8:
      - 5
